
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 
      
              
mongodb:
  uri:
    read: mongodb://sa:${MONGO-DB-PASS_READ:invalidPassword}@mongo-read-db:27017/mongo-read-db?authSource=admin
    write: mongodb://sa:${MONGO-DB-PASS_WRITE:invalidPassword}@mongo-write-db:27017/mongo-write-db?authSource=admin
     